### ISSUE TITLE
Cache Powershell modules in Travis CI

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/data-safe-haven#1262]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] ~This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.~ This is an improvement to the build process
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Configure Travis CI to cache installed Powershell modules. It currently takes ~30 minutes to install the Powershell modules required to run about 30 seconds of Powershell tests and we do this for every change pushed to a PR, whether or not any changes are made to the Powershell code.

## :steam_locomotive: How could this be done?

I'm looking to take the approach at https://github.com/PowerShell/PowerShell/pull/6003/files, replacing the package install directory with `$HOME/.local/share/powershell/Modules/ ` after inspecting a Linux Travis CI build log to see where modules are getting installed.

I'm not sure we'll know if the latest version of powershell has changed, so I propose not including a version environment variable, instead relying on the package versions being part of the full path and therefore when a newer version of a package is pulled, there will be a cache miss. (example full path is '/home/travis/.local/share/powershell/Modules/Az.Accounts/2.9.1`, with `$HOME` resolving to `/home/travis/` on Linux VMs on Travis CI.

```yaml
# travis-ci will quit using the cache if an enviroment variable changes
env:
  - CACHE_VERSION=netcoreapp.2.0.5

# timeout uploading cache after 6 minutes (360 seconds)
cache:
  timeout: 360
  directories:
    - $HOME/.nuget
    - $HOME/.dotnet
    - $HOME/Library/Caches/Homebrew
```
