### ISSUE TITLE
Replace install_deb script with ansible commands

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2095]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Replace the `install_deb.sh` script with native Ansible

## :steam_locomotive: How could this be done?

Suggestion from #2093 

```yaml
    - name: Install deb packages
      tags: apt
      block:
        - ansible.builtin.stat:
            path: "{{ item.creates }}"
          register: app

        - ansible.builtin.get_url:
            url: "{{ item.source }}"
            dest: /tmp/debfile.deb
            checksum: "{{ item.checksum }}"
          when: not app.exists

        - ansible.builtin.apt:
            deb: /tmp/debfile.deb
            state: present
          when: not app.exists
      loop: "{{ deb_packages[ansible_facts.distribution_release] }}"
```
