### ISSUE TITLE
Updating single workspace_sku - failing deployment

### ISSUE THREAD

**Issue by helen-d-little** [alan-turing-institute/data-safe-haven#2365]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **managing** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** 5.2.1

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

Updating a workspace_sku on a deployed SRE fails when *replacing* `Standard_D8s_v5` with `Standard_D2s_v3`

#### initial config:
```
...
sre:
  admin_email_address: trustedresearch@turing.ac.uk
  admin_ip_addresses:
  - 193.60.220.253/32
  data_provider_ip_addresses:
  - 193.60.220.253/32
  databases: []
  remote_desktop:
    allow_copy: true
    allow_paste: true
  research_user_ip_addresses: "Internet"
  software_packages: any
  storage_quota_gb:
    home: 100
    shared: 100
  timezone: Europe/London
  workspace_skus:
  - Standard_D8s_v5
```

#### Updated Config:
```
...
sre:
  admin_email_address: trustedresearch@turing.ac.uk
  admin_ip_addresses:
  - 193.60.220.253/32
  data_provider_ip_addresses:
  - 193.60.220.253/32
  databases: []
  remote_desktop:
    allow_copy: true
    allow_paste: true
  research_user_ip_addresses: "Internet"
  software_packages: any
  storage_quota_gb:
    home: 100
    shared: 100
  timezone: Europe/London
  workspace_skus:
  - Standard_D2s_v3
```

#### Tail of output:
`
Pulumi error:  ~  azure-native:compute:VirtualMachine sre_workspaces_vm_workspace_01 updating 
(3s) [diff: ~hardwareProfile,tags]; error: PUT                                          
https://management.azure.com/subscriptions/40e70a5a-4947-4175-9730-8c4e49131296/resourceGroups/shm-prod5-sre-test521-rg
/providers/Microsoft.Compute/virtualMachines/shm-prod5-sre-test521-vm-workspace-01                                     
Pulumi error:  ~  azure-native:compute:VirtualMachine sre_workspaces_vm_workspace_01 **updating     
failed** [diff: ~hardwareProfile,tags]; error: PUT                                      
https://management.azure.com/subscriptions/40e70a5a-4947-4175-9730-8c4e49131296/resourceGroups/shm-prod5-sre-test521-rg
/providers/Microsoft.Compute/virtualMachines/shm-prod5-sre-test521-vm-workspace-01                                     
Pulumi error:     pulumi:pulumi:Stack data-safe-haven-shm-prod5-sre-test521 running error:            
update failed                                                                                                 
Pulumi error:     error: update failed                                                                
Pulumi error:     error: PUT                                                                             
https://management.azure.com/subscriptions/40e70a5a-4947-4175-9730-8c4e49131296/resourceGroups/shm-prod5-sre-test521-rg
/providers/Microsoft.Compute/virtualMachines/shm-prod5-sre-test521-vm-workspace-01                                     
Pulumi error:  stderr:                                                                                                 
Pulumi update failed.                                                                                                  
Pulumi deployment failed.                                                                                              
Could not deploy Secure Research Environment 'test521'.
`

[overwrite_sku_test.txt](https://github.com/user-attachments/files/18457968/overwrite_sku_test.txt)
